---
- name: craete web server
  hosts: all
  tasks:
  - name: install package
    yum:
      name: vsftpd
      state: latest
      
  - firewalld:
      port: 20-21/tcp
      permanent: yes
      state: present
      
  - name: start service
    service:
      name: vsftpd
      enabled: yes
    notify:
      - start apache
          
  handlers:
    - name: start apache
      service:
        name: vsftpd
        state: started
        
