---
- name: craete web server
  hosts: all
  tasks:
  - name: install package
    yum:
      name: vsftpd, docker 
      state: latest
      
  - firewalld:
      service: ftp
      immediate: yes
      permanent: true
      state: enabled
      
  - name: start service
    service:
      name: vsftpd, docker
      enabled: yes
    notify:
      - start apache
          
  handlers:
    - name: start apache
      service:
        name: vsftpd, docker
        state: started
        
